### ISSUE TITLE
Is there a way to get apk

### ISSUE THREAD

**Issue by nepalicana** [hbvj99/nettv-box#1]
I was wondering if there is anyway to get the NetTv launcher apk from the official NetTv boxes, if we can get that then it might be easy for other tv boxes to install on it and don’t have to relay on the isp provided boxes.

**Comment by hbvj99** [comment]
Hi @nepalicana, you can follow this [procedure](https://vijaypathak.com.np/2019/11/nettv-box-hack.html#method-2-install-on-the-top-of-offical-nettv) to bypass and install/backup other apps. 

Just making a copy of launchers won't work since its just tv launcher, but almost all firmware comes pre-rooted you could easily modify settings. Even if you manage to make it work, it requires MAC to be registered in ISP.
